project:
  title: "Shiny application frameworks"
  type: website

website:
  title: "Shiny Frameworks"
  repo-url: https://github.com/mjfrigaard/sfw
  repo-branch: main
  repo-actions: [issue]
  navbar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/mjfrigaard/sfw
          - text: Report an issue
            url:  https://github.com/mjfrigaard/sfw/issues
    left:
      - href: index.qmd
        text: Home
      - href: golem.qmd
        text: golem
      - href: leprechaun.qmd
        text: leprechaun
      #- href: charpente.qmd
      #  text: charpente
      - href: rhino.qmd
        text: rhino

format:
  html:
    #code-fold: show
    code-summary: 'show/hide'
    # code-overflow:
    #code-link: false
    #code-overflow: wrap
    #code-annotations: true
    lightbox: true
    code-block-bg: "#f8f8f8"
    code-block-border-left: "#99bbc9"
    toc: true
    df-print: paged
    toc-depth: 5
    toc-location: right
    toc-title: Contents
    code-annotations: hover
    dpi: 320
    fig-format: retina
    fig-asp: 0.618
    fontsize: 1.015em
    linestretch: 1.30
    theme: [yeti, custom.scss]
    highlight-style: arrow
    number-sections: false

execute:
  echo: true
  eval: true

