project:
  title: "Shiny application frameworks"
  type: website

website:
  title: "Shiny Frameworks"
  repo-url: https://github.com/mjfrigaard/shinyap
  repo-branch: main
  repo-actions: [issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: golem.qmd
        text: golem
      - href: leprechaun.qmd
        text: leprechaun
      - href: rhino.qmd
        text: rhino

format:
  html:
    #code-fold: show
    #code-summary: 'show/hide'
    code-annotations: hover
    #code-overflow: wrap
    #code-link: false
    #code-overflow: wrap
    #code-link: false
    #code-block-bg: "#f8f8f8"
    #code-block-border-left: "#99bbc9"
    #code-annotations: true
    #code-block-bg: "#f8f8f8"
    #code-block-border-left: "#99bbc9"
    df-print: tibble
    dpi: 320
    fig-format: retina
    fig-asp: 0.618
    fontsize: 1.075em
    linestretch: 1.25
    theme: [cosmo, custom.scss]
    highlight-style: arrow
    number-sections: false
    
execute:
  echo: true 
  eval: true

