---
title: "Tests and Coverage"
date: "`r format(Sys.time(), '%d %B, %Y %H:%M:%S')`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Tests and Coverage}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE
)
```

## test-mod_aes_inputs

```{r mod-aes-inputs}
describe("Feature: Scatter Plot Configuration in gap movies app
      As a user
      I want the initial graph pre-configured with aesthetics,
      So that I can change the inputs and see a meaningful visualization.",
  code = {
    describe("Background: Initial ...
         Given the movie review application is loaded
         And the initial alpha value is [0.7]
         And the initial size value is [3]
         And the initial title value is [NULL]",
      code = {
        
      })
    })
```


## test-mod_var_inputs

```{r mod-var-inputs}
describe("Feature: Scatter Plot Configuration in gap movies app
      As a user
      I want the initial graph pre-configured with variables,
      So that I can change the inputs and see a meaningful visualization.",
  code = {
    describe("Background: Initial scatter plot x, y, color values
         Given the movie review application is loaded
         And the initial x-axis value is [IMDB Rating]
         And the initial y-axis value is [Audience Score]
         And the initial color value is [MPAA Rating]",
      code = {
      })
    })
```

## test-mod_scatter_display

```{r}
describe("Feature: Scatter Plot Configuration in Movie Review Application
      As a user 
      I want the initial graph pre-configured with variables and aesthetics,
      So that I can immediately see a meaningful visualization.",
  code = {
  })
```

